language: node_js
sudo: no
dist: trusty
node_js:
  - "7"
env:
  - CXX=g++-6 MONGODB=127.0.0.1
install:
  - find /usr -name '*poppler*.so*'
  - npm install -g npm@latest
  - npm cache clean
  - npm install --dev
  - npm install coveralls
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - r-packages-trusty
      - mongodb-3.0-precise
    packages:
      - g++-6
      - libpoppler-glib-dev
      - mongodb-org
script:
  - npm run webpack && ./test/perpareDatabase.sh && npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
