language: node_js
sudo: no
node_js:
  - "7"
env:
  - CXX=g++-4.8
  - MONGODB=127.0.0.1
install:
  - npm install -g npm@latest
  - npm cache clean
  - npm install --dev
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - ./test/perpareDatabase.sh && npm run test
